services:
  postgres:
    image: postgres:16

    container_name: polls_postgres

    environment:
      POSTGRES_DB: polls
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345

    ports:
      - "5436:5432"